
services:
  postgres:
    image: postgres:latest
    container_name: quiz_db_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quiz_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: quiz_app_container
    depends_on:
      - postgres
    environment:
       DB_HOST: postgres
       DB_PORT: 5432
       DB_USER: user
       DB_PASSWORD: password
       DB_NAME: quiz_db
    ports:
        - "8080:8080"

volumes:
  pg_data:


